
=head1 HDR USER MANUAL

This document will help you understand how to use the I<hdr> command part of the L<Data::HexDump::Range> module. The latest 
version is  at L<http://search.cpan.org/search?query=Data%3A%3AHexDump%3A%3ARange>.

It is important to understand that I<hdr> is a visualisation tool. It does not understand your data.

=head2 The hdr command

=head2 When in the hexdump land, do as hexdumper do

 >$ hdr file_name

=begin html

<pre style ="font-family: monospace; background-color: #000 ;">

<span style='color:#fff;'>00000000</span> <span style='color:#0f0;'>63 6f 6d 6d 69 74 20 38 38 30 39 63 38 65 38 34 </span> <span style='color:#0f0;'>commit 8809c8e84</span> 
<span style='color:#fff;'>00000010</span> <span style='color:#0f0;'>65 62 33 32 33 62 62 61 61 33 36 36 39 65 39 34 </span> <span style='color:#0f0;'>eb323bbaa3669e94</span> 
<span style='color:#fff;'>00000020</span> <span style='color:#0f0;'>38 62 36 38 35 30 32 36 63 33 35 66 61 35 39 20 </span> <span style='color:#0f0;'>8b685026c35fa59 </span> 
<span style='color:#fff;'>00000030</span> <span style='color:#0f0;'>28 48 45 41 44 2c 20 6d 61 73 74 65 72 29 0a 41 </span> <span style='color:#0f0;'>(HEAD, master).A</span> 
<span style='color:#fff;'>00000040</span> <span style='color:#0f0;'>75 74 68 6f 72 3a 20 6e 61 64 69 6d 20 6b 68 65 </span> <span style='color:#0f0;'>uthor: nadim khe</span> 
<span style='color:#fff;'>00000050</span> <span style='color:#0f0;'>6d 69 72 20 3c 6e 6b 68 40 63 70 61 6e 2e 6f 72 </span> <span style='color:#0f0;'>mir <nkh@cpan.or</span> 
<span style='color:#fff;'>00000060</span> <span style='color:#0f0;'>67 3e 0a 44 61 74 65 3a 20 20 20 53 75 6e 20 41 </span> <span style='color:#0f0;'>g>.Date:   Sun A</span> 
<span style='color:#fff;'>00000070</span> <span style='color:#0f0;'>70 72 20 31 38 20 30 33 3a 33 32 3a 30 33 20 32 </span> <span style='color:#0f0;'>pr 18 03:32:03 2</span> 
<span style='color:#fff;'>00000080</span> <span style='color:#0f0;'>30 31 30 20 2b 30 32 30 30 0a 0a 20 20 20 20 41 </span> <span style='color:#0f0;'>010 +0200..    A</span> 
</pre>

=end html

=head2 output format

The data displayed is the same in all the formats hdr supports. The default output format is B<ANSI>. B<ASCII> is like B<ANSI> without the colors.

=head3 ASCII

  00000000 63 6f 6d 6d 69 74 20 38 38 30 39 63 38 65 38 34  commit 8809c8e84
  00000010 65 62 33 32 33 62 62 61 61 33 36 36 39 65 39 34  eb323bbaa3669e94
  00000020 38 62 36 38 35 30 32 36 63 33 35 66 61 35 39 20  8b685026c35fa59
  00000030 28 48 45 41 44 2c 20 6d 61 73 74 65 72 29 0a 41  (HEAD, master).A
  00000040 75 74 68 6f 72 3a 20 6e 61 64 69 6d 20 6b 68 65  uthor: nadim khe
  00000050 6d 69 72 20 3c 6e 6b 68 40 63 70 61 6e 2e 6f 72  mir <nkh@cpan.or
  00000060 67 3e 0a 44 61 74 65 3a 20 20 20 53 75 6e 20 41  g>.Date:   Sun A
  00000070 70 72 20 31 38 20 30 33                          pr 18 03

=head3 ANSI

B<ANSI> can't be rendered from pod but it look like the <HTML> below

=head3 HTML

=begin html

<pre style ="font-family: monospace; background-color: #000 ;">

<span style='color:#fff;'>00000000</span> <span style='color:#0f0;'>63 6f 6d 6d 69 74 20 38 38 30 39 63 38 65 38 34 </span> <span style='color:#0f0;'>commit 8809c8e84</span> 
<span style='color:#fff;'>00000010</span> <span style='color:#0f0;'>65 62 33 32 33 62 62 61 61 33 36 36 39 65 39 34 </span> <span style='color:#0f0;'>eb323bbaa3669e94</span> 
<span style='color:#fff;'>00000020</span> <span style='color:#0f0;'>38 62 36 38 35 30 32 36 63 33 35 66 61 35 39 20 </span> <span style='color:#0f0;'>8b685026c35fa59 </span> 
<span style='color:#fff;'>00000030</span> <span style='color:#0f0;'>28 48 45 41 44 2c 20 6d 61 73 74 65 72 29 0a 41 </span> <span style='color:#0f0;'>(HEAD, master).A</span> 
<span style='color:#fff;'>00000040</span> <span style='color:#0f0;'>75 74 68 6f 72 3a 20 6e 61 64 69 6d 20 6b 68 65 </span> <span style='color:#0f0;'>uthor: nadim khe</span> 
<span style='color:#fff;'>00000050</span> <span style='color:#0f0;'>6d 69 72 20 3c 6e 6b 68 40 63 70 61 6e 2e 6f 72 </span> <span style='color:#0f0;'>mir <nkh@cpan.or</span> 
<span style='color:#fff;'>00000060</span> <span style='color:#0f0;'>67 3e 0a 44 61 74 65 3a 20 20 20 53 75 6e 20 41 </span> <span style='color:#0f0;'>g>.Date:   Sun A</span> 
<span style='color:#fff;'>00000070</span> <span style='color:#0f0;'>70 72 20 31 38 20 30 33                         </span> <span style='color:#0f0;'>pr 18 03        </span> 

</pre>

=end html

=head3 Showing the column header and the rulers

Command: I<hdr -col -rul your_file>

=begin html

<pre style ="font-family: monospace; background-color: #000 ;">

<span style='color:#fff;'>OFFSET   HEX_DUMP                                         ASCII_DUMP       </span> 
<span style='color:#fff;'>         0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f   0123456789012345 </span> 
<span style='color:#fff;'>00000000</span> <span style='color:#0f0;'>63 6f 6d 6d 69 74 20 38 38 30 39 63 38 65 38 34 </span> <span style='color:#0f0;'>commit 8809c8e84</span> 
<span style='color:#fff;'>00000010</span> <span style='color:#0f0;'>65 62 33 32 33 62 62 61 61 33 36 36 39 65 39 34 </span> <span style='color:#0f0;'>eb323bbaa3669e94</span> 
<span style='color:#fff;'>00000020</span> <span style='color:#0f0;'>38 62 36 38 35 30 32 36 63 33 35 66 61 35 39 20 </span> <span style='color:#0f0;'>8b685026c35fa59 </span> 

</pre>

=end html

=head2 intput 

=head2 from file or stdin

=head2 too little data

=head2 too much data

--max_size

head -c 

=head2 Displaying selected chunks

=head2 range descritption

=head3 from command line

=head3 from file

=head4 simple

=head4 advance

 use strict ;
 use warnings ;
  
 my $data_range = # definition to re-use
 	[
 	  ['data header', 5, 'blue on_cyan'],
 	  ['data', 20, 'blue on_bright_yellow'],
 	] ;
 
 my $structured_range = 
 	[
 	    ['zero size', 0],
 	  [
 	    ['magic cookie', 12, 'red'],
 	    ['padding', 32, 'yellow'],
 	    $data_range, 
 	  ],
              ['other zero size', 0],		
 	  [
 	    ['extra data', 18, undef],
 	      [
 	      $data_range, 
 	      ['footer', 4, 'bright_yellow on_red'],
  	    ]
   	  ],
  	] ; 
 	
 $structured_range ;

See L<Advanced usage>

=head2 Bitfields

command: hdr  --col -display_ruler -r 'data,1 :DATA,4:c,b9:d,b3 :e,x4b5     :the end,8:x,b3:data,47:v,x90b8' lib/Data/HexDump/Range.pm -format HTML  > file.html

=head3 Vertical mode

=begin html

<pre style ="font-family: monospace; background-color: #000 ;">

<span style='color:#fff;'>RANGE_NAME       OFFSET   CUMULATI HEX_DUMP                                         ASCII_DUMP       </span> 
<span style='color:#fff;'>                                   0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f   0123456789012345 </span> 
<span style='color:#0f0;'>data            </span> <span style='color:#fff;'>00000000</span> <span style='color:#fff;'>00000000</span> <span style='color:#0f0;'>0a                                              </span> <span style='color:#0f0;'>.               </span> 
<span style='color:#ff0;'>DATA            </span> <span style='color:#fff;'>00000001</span> <span style='color:#fff;'>00000000</span> <span style='color:#ff0;'>70 61 63 6b                                     </span> <span style='color:#ff0;'>pack            </span> 
<span style='color:#0ff;'>.c              </span> <span style='color:#0ff;'>00 .. 08</span> <span style='color:#0ff;'>        </span> <span style='color:#0ff;'>-- -- 00 e0    011100000----------------------- </span> <span style='color:#0ff;'>.bitfield: --.à </span> 
<span style='color:#f00;'>.d              </span> <span style='color:#f00;'>00 .. 02</span> <span style='color:#f00;'>        </span> <span style='color:#f00;'>-- -- -- 03    011----------------------------- </span> <span style='color:#f00;'>.bitfield: ---. </span> 
<span style='color:#fff;'>.e              </span> <span style='color:#fff;'>04 .. 08</span> <span style='color:#fff;'>        </span> <span style='color:#fff;'>-- -- -- 00    ----00000----------------------- </span> <span style='color:#fff;'>.bitfield: ---. </span> 
<span style='color:#0f0;'>the end         </span> <span style='color:#fff;'>00000005</span> <span style='color:#fff;'>00000000</span> <span style='color:#0f0;'>61 67 65 20 44 61 74 61                         </span> <span style='color:#0f0;'>age Data        </span> 
<span style='color:#ff0;'>.x              </span> <span style='color:#ff0;'>00 .. 02</span> <span style='color:#ff0;'>        </span> <span style='color:#ff0;'>-- -- -- 03    011----------------------------- </span> <span style='color:#ff0;'>.bitfield: ---. </span> 
<span style='color:#0ff;'>data            </span> <span style='color:#fff;'>0000000d</span> <span style='color:#fff;'>00000000</span> <span style='color:#0ff;'>3a 3a 48 65 78 44 75 6d 70 3a 3a 52 61 6e 67 65 </span> <span style='color:#0ff;'>::HexDump::Range</span> 
<span style='color:#0ff;'>data            </span> <span style='color:#fff;'>0000001d</span> <span style='color:#fff;'>00000010</span> <span style='color:#0ff;'>20 3b 0a 0a 75 73 65 20 73 74 72 69 63 74 3b 0a </span> <span style='color:#0ff;'> ;..use strict;.</span> 
<span style='color:#0ff;'>data            </span> <span style='color:#fff;'>0000002d</span> <span style='color:#fff;'>00000020</span> <span style='color:#0ff;'>75 73 65 20 77 61 72 6e 69 6e 67 73 20 3b 0a    </span> <span style='color:#0ff;'>use warnings ;. </span> 
<span style='color:#f00;'>.v              </span> <span style='color:#f00;'>90 .. 97</span> <span style='color:#f00;'>        </span> <span style='color:#f00;'>-- -- -- 49    ------------------------01001001 </span> <span style='color:#f00;'>.bitfield: ---I </span> 

</pre>

=end html

=head3 Horizontal mode

=begin html

<pre style ="font-family: monospace; background-color: #000 ;">

<span style='color:#fff;'>OFFSET   BITFIELD HEX_DUMP                                         ASCII_DUMP       RANGE_NAME                  </span> 
<span style='color:#fff;'>                  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f   0123456789012345                             </span> 
<span style='color:#fff;'>00000000</span><span style='color:#fff;'></span><span style='color:#fff;'></span><span style='color:#fff;'></span> <span style='color:#fff;'>        </span><span style='color:#fff;'></span><span style='color:#fff;'></span><span style='color:#fff;'></span> <span style='color:#0f0;'>0a </span><span style='color:#ff0;'>70 61 63 6b </span><span style='color:#0f0;'>61 67 65 20 44 61 74 61 </span><span style='color:#0ff;'>3a 3a 48 </span> <span style='color:#0f0;'>.</span><span style='color:#ff0;'>pack</span><span style='color:#0f0;'>age Data</span><span style='color:#0ff;'>::H</span> <span style='color:#0f0;'>data</span><span style='color:#fff;'>, </span><span style='color:#ff0;'>DATA</span><span style='color:#fff;'>, </span><span style='color:#0f0;'>the end</span><span style='color:#fff;'>, </span><span style='color:#0ff;'>data</span><span style='color:#fff;'>, </span> 
<span style='color:#0ff;'>00 .. 08</span> <span style='color:#ff0;'>DATA    </span> <span style='color:#0ff;'>-- -- 00 e0    011100000----------------------- </span> <span style='color:#0ff;'>.bitfield: --.à </span> <span style='color:#0ff;'>.c              </span> 
<span style='color:#f00;'>00 .. 02</span> <span style='color:#ff0;'>DATA    </span> <span style='color:#f00;'>-- -- -- 03    011----------------------------- </span> <span style='color:#f00;'>.bitfield: ---. </span> <span style='color:#f00;'>.d              </span> 
<span style='color:#fff;'>04 .. 08</span> <span style='color:#ff0;'>DATA    </span> <span style='color:#fff;'>-- -- -- 00    ----00000----------------------- </span> <span style='color:#fff;'>.bitfield: ---. </span> <span style='color:#fff;'>.e              </span> 
<span style='color:#ff0;'>00 .. 02</span> <span style='color:#0f0;'>the end </span> <span style='color:#ff0;'>-- -- -- 03    011----------------------------- </span> <span style='color:#ff0;'>.bitfield: ---. </span> <span style='color:#ff0;'>.x              </span> 
<span style='color:#fff;'>00000010</span> <span style='color:#fff;'>        </span> <span style='color:#0ff;'>65 78 44 75 6d 70 3a 3a 52 61 6e 67 65 20 3b 0a </span> <span style='color:#0ff;'>exDump::Range ;.</span> <span style='color:#0ff;'>data</span><span style='color:#fff;'>, </span> 
<span style='color:#fff;'>00000020</span> <span style='color:#fff;'>        </span> <span style='color:#0ff;'>0a 75 73 65 20 73 74 72 69 63 74 3b 0a 75 73 65 </span> <span style='color:#0ff;'>.use strict;.use</span> <span style='color:#0ff;'>data</span><span style='color:#fff;'>, </span> 
<span style='color:#fff;'>00000030</span> <span style='color:#fff;'>        </span> <span style='color:#0ff;'>20 77 61 72 6e 69 6e 67 73 20 3b 0a             </span> <span style='color:#0ff;'> warnings ;.    </span> <span style='color:#0ff;'>data</span><span style='color:#fff;'>, </span> 
<span style='color:#f00;'>90 .. 97</span> <span style='color:#0ff;'>data    </span> <span style='color:#f00;'>-- -- -- 49    ------------------------01001001 </span> <span style='color:#f00;'>.bitfield: ---I </span> <span style='color:#f00;'>.v              </span> 

</pre>

=end html

=head3 Bitfields need enough data!

B<No data to start with>

=begin html

<pre style ="font-family: monospace; background-color: #000 ;">

<span style='color:#fff;'>OFFSET   BITFIELD HEX_DUMP                                         ASCII_DUMP       RANGE_NAME                  </span> 
<span style='color:#fff;'>                  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f   0123456789012345                             </span> 
<span style='color:#fff;'>00000000</span><span style='color:#fff;'></span><span style='color:#fff;'></span><span style='color:#fff;'></span> <span style='color:#fff;'>        </span><span style='color:#fff;'></span><span style='color:#fff;'></span><span style='color:#fff;'></span> <span style='color:#0f0;'>0a </span><span style='color:#ff0;'>70 61 63 6b </span><span style='color:#0f0;'>61 67 65 20 44 61 74 61 </span><span style='color:#0ff;'>3a 3a 48 </span> <span style='color:#0f0;'>.</span><span style='color:#ff0;'>pack</span><span style='color:#0f0;'>age Data</span><span style='color:#0ff;'>::H</span> <span style='color:#0f0;'>data</span><span style='color:#fff;'>, </span><span style='color:#ff0;'>DATA</span><span style='color:#fff;'>, </span><span style='color:#0f0;'>the end</span><span style='color:#fff;'>, </span><span style='color:#0ff;'>data</span><span style='color:#fff;'>, </span> 
<span style='color:#0f0;'>00 .. 03</span> <span style='color:#fff;'>?       </span> <span style='color:#0f0;'>?                                               </span> <span style='color:#0f0;'>?               </span> <span style='color:#0f0;'>.a              </span> 
<span style='color:#ff0;'>00 .. 02</span> <span style='color:#fff;'>?       </span> <span style='color:#ff0;'>?                                               </span> <span style='color:#ff0;'>?               </span> <span style='color:#ff0;'>.b              </span> 
<span style='color:#0ff;'>00 .. 00</span> <span style='color:#fff;'>?       </span> <span style='color:#0ff;'>?                                               </span> <span style='color:#0ff;'>?               </span> <span style='color:#0ff;'>.x              </span> 
<span style='color:#f00;'>00 .. 00</span> <span style='color:#fff;'>?       </span> <span style='color:#f00;'>?                                               </span> <span style='color:#f00;'>?               </span> <span style='color:#f00;'>.y              </span> 
<span style='color:#fff;'>00 .. 00</span> <span style='color:#fff;'>?       </span> <span style='color:#fff;'>?                                               </span> <span style='color:#fff;'>?               </span> <span style='color:#fff;'>.z              </span> 
<span style='color:#0ff;'>00 .. 08</span> <span style='color:#ff0;'>DATA    </span> <span style='color:#0ff;'>-- -- 00 e0    011100000----------------------- </span> <span style='color:#0ff;'>.bitfield: --.à </span> <span style='color:#0ff;'>.c              </span> 
<span style='color:#f00;'>00 .. 02</span> <span style='color:#ff0;'>DATA    </span> <span style='color:#f00;'>-- -- -- 03    011----------------------------- </span> <span style='color:#f00;'>.bitfield: ---. </span> <span style='color:#f00;'>.d              </span> 
<span style='color:#fff;'>04 .. 08</span> <span style='color:#ff0;'>DATA    </span> <span style='color:#fff;'>-- -- -- 00    ----00000----------------------- </span> <span style='color:#fff;'>.bitfield: ---. </span> <span style='color:#fff;'>.e              </span> 
<span style='color:#ff0;'>00 .. 02</span> <span style='color:#0f0;'>the end </span> <span style='color:#ff0;'>-- -- -- 03    011----------------------------- </span> <span style='color:#ff0;'>.bitfield: ---. </span> <span style='color:#ff0;'>.x              </span> 
<span style='color:#fff;'>00000010</span> <span style='color:#fff;'>        </span> <span style='color:#0ff;'>65 78 44 75 6d 70 3a 3a 52 61 6e 67 65 20 3b 0a </span> <span style='color:#0ff;'>exDump::Range ;.</span> <span style='color:#0ff;'>data</span><span style='color:#fff;'>, </span> 
<span style='color:#fff;'>00000020</span> <span style='color:#fff;'>        </span> <span style='color:#0ff;'>0a 75 73 65 20 73 74 72 69 63 74 3b 0a 75 73 65 </span> <span style='color:#0ff;'>.use strict;.use</span> <span style='color:#0ff;'>data</span><span style='color:#fff;'>, </span> 
<span style='color:#fff;'>00000030</span> <span style='color:#fff;'>        </span> <span style='color:#0ff;'>20 77 61 72 6e 69 6e 67 73 20 3b 0a             </span> <span style='color:#0ff;'> warnings ;.    </span> <span style='color:#0ff;'>data</span><span style='color:#fff;'>, </span> 
<span style='color:#f00;'>90 .. 97</span> <span style='color:#0ff;'>data    </span> <span style='color:#f00;'>-- -- -- 49    ------------------------01001001 </span> <span style='color:#f00;'>.bitfield: ---I </span> <span style='color:#f00;'>.v              </span> 

</pre>

=end html

B<not enough data>

=begin html

<pre style ="font-family: monospace; background-color: #000 ;">

<span style='color:#fff;'>OFFSET   BITFIELD HEX_DUMP                                         ASCII_DUMP       RANGE_NAME                  </span> 
<span style='color:#fff;'>                  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f   0123456789012345                             </span> 
<span style='color:#fff;'>00000000</span><span style='color:#fff;'></span><span style='color:#fff;'></span><span style='color:#fff;'></span> <span style='color:#fff;'>        </span><span style='color:#fff;'></span><span style='color:#fff;'></span><span style='color:#fff;'></span> <span style='color:#0f0;'>0a </span><span style='color:#ff0;'>70 61 63 6b </span><span style='color:#0f0;'>61 67 65 20 44 61 74 61 </span><span style='color:#0ff;'>3a 3a 48 </span> <span style='color:#0f0;'>.</span><span style='color:#ff0;'>pack</span><span style='color:#0f0;'>age Data</span><span style='color:#0ff;'>::H</span> <span style='color:#0f0;'>data</span><span style='color:#fff;'>, </span><span style='color:#ff0;'>DATA</span><span style='color:#fff;'>, </span><span style='color:#0f0;'>the end</span><span style='color:#fff;'>, </span><span style='color:#0ff;'>data</span><span style='color:#fff;'>, </span> 
<span style='color:#0ff;'>00 .. 48</span> <span style='color:#ff0;'>DATA    </span> <span style='color:#0ff;'>?                                               </span> <span style='color:#0ff;'>?               </span> <span style='color:#0ff;'>.c              </span> 
<span style='color:#f00;'>49 .. 51</span> <span style='color:#ff0;'>DATA    </span> <span style='color:#f00;'>?                                               </span> <span style='color:#f00;'>?               </span> <span style='color:#f00;'>.d              </span> 
<span style='color:#fff;'>04 .. 08</span> <span style='color:#ff0;'>DATA    </span> <span style='color:#fff;'>-- -- -- 00    ----00000----------------------- </span> <span style='color:#fff;'>.bitfield: ---. </span> <span style='color:#fff;'>.e              </span> 
<span style='color:#ff0;'>00 .. 02</span> <span style='color:#0f0;'>the end </span> <span style='color:#ff0;'>-- -- -- 03    011----------------------------- </span> <span style='color:#ff0;'>.bitfield: ---. </span> <span style='color:#ff0;'>.x              </span> 
<span style='color:#fff;'>00000010</span> <span style='color:#fff;'>        </span> <span style='color:#0ff;'>65 78 44 75 6d 70 3a 3a 52 61 6e 67 65 20 3b 0a </span> <span style='color:#0ff;'>exDump::Range ;.</span> <span style='color:#0ff;'>data</span><span style='color:#fff;'>, </span> 
<span style='color:#fff;'>00000020</span> <span style='color:#fff;'>        </span> <span style='color:#0ff;'>0a 75 73 65 20 73 74 72 69 63 74 3b 0a 75 73 65 </span> <span style='color:#0ff;'>.use strict;.use</span> <span style='color:#0ff;'>data</span><span style='color:#fff;'>, </span> 
<span style='color:#fff;'>00000030</span> <span style='color:#fff;'>        </span> <span style='color:#0ff;'>20 77 61 72 6e 69 6e 67 73 20 3b 0a             </span> <span style='color:#0ff;'> warnings ;.    </span> <span style='color:#0ff;'>data</span><span style='color:#fff;'>, </span> 
<span style='color:#f00;'>90 .. 97</span> <span style='color:#0ff;'>data    </span> <span style='color:#f00;'>-- -- -- 49    ------------------------01001001 </span> <span style='color:#f00;'>.bitfield: ---I </span> <span style='color:#f00;'>.v              </span> 

</pre>

=end html

=head1 Advanced usage

verify your data

display data errors with hdr

=head3 gathering data

=head2 dynamic range generation

=head2 Bash completion script

B<hdr> can generate a bash completion script 

 $> hdr --generate_bash_completion option > hdr_completion
 $> source hdr_completion
 
=head2 Helping out

You can contribute by:

=over 2

=item * report error! L<RT ...>

=item * send some examples of your data/output

=item * send parsers or other scripts that you use hdr in

=item * send new requirement, patches, documentation enhancements

=item * pass the word around so more people use hdr and I get more feedback

=item * plant a tree, save a cat/dog, bike instead for driving, spread some love around you :)

=back

=head1 AUTHOR

	Nadim ibn hamouda el Khemir
	CPAN ID: NKH
	mailto: nadim@cpan.org

=head1 COPYRIGHT & LICENSE

Copyright 2010 Nadim Khemir.

This program is free software; you can redistribute it and/or
modify it under the terms of either:

=over 4

=item * the GNU General Public License as published by the Free
Software Foundation; either version 1, or (at your option) any
later version, or

=item * the Artistic License version 2.0.

=back

=head1 SUPPORT

You can also look for information at:

=over 4

=item * RT: CPAN's request tracker

Please report any bugs or feature requests to  L <bug-data-hexdump-range@rt.cpan.org>.

=back

=head1 SEE ALSO

B<hexd> from libma L<http://www.ioplex.com/~miallen/libmba/>

=cut
